//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Realty()
        {
            this.Contracts = new HashSet<Contracts>();
        }
    
        public int RealtyID { get; set; }
        public int OwnerID { get; set; }
        public int RealtyTypeID { get; set; }
        public string Address { get; set; }
        public decimal SquareMeters { get; set; }
        public Nullable<int> Floor { get; set; }
        public string Description { get; set; }
        public bool IsOwned { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
        public virtual Owners Owners { get; set; }
        public virtual RealtyTypes RealtyTypes { get; set; }
    }
}
